export interface Problem {
  name: string;
  lc: string;
  gfg: string;
}

export interface Subsection {
  id: string;
  title: string;
  problems: Problem[];
}

export interface Step {
  id: string;
  step: number;
  title: string;
  color: string;
  icon: string;
  subsections: Subsection[];
}

export const DSA_DATA: Step[] = [
  {id:'s1',step:1,title:'Learn the Basics',color:'#0ea5e9',icon:'🧱',
  subsections:[
    {id:'s1-1',title:'1.1 · Things to Know in C++/Java/Python',problems:[
      {name:'User Input / Output',lc:'N/A',gfg:'N/A'},
      {name:'Data Types',lc:'N/A',gfg:'https://www.geeksforgeeks.org/data-types-in-c/'},
      {name:'If-Else Statements',lc:'N/A',gfg:'N/A'},
      {name:'Switch Statements',lc:'N/A',gfg:'N/A'},
      {name:'Arrays & Strings',lc:'N/A',gfg:'N/A'},
      {name:'For Loops',lc:'N/A',gfg:'N/A'},
      {name:'While Loops',lc:'N/A',gfg:'N/A'},
      {name:'Functions (Pass by Value, Reference)',lc:'N/A',gfg:'N/A'},
      {name:'Time Complexity Basics',lc:'N/A',gfg:'https://www.geeksforgeeks.org/understanding-time-complexity-simple-examples/'},
    ]},
    {id:'s1-2',title:'1.2 · Build-up Mathematical Knowledge',problems:[
      {name:'Count Digits',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/count-digits5716/1'},
      {name:'Reverse a Number',lc:'https://leetcode.com/problems/reverse-integer/',gfg:'https://practice.geeksforgeeks.org/problems/reverse-digits0316/1'},
      {name:'Check Palindrome',lc:'https://leetcode.com/problems/palindrome-number/',gfg:'https://practice.geeksforgeeks.org/problems/palindrome0746/1'},
      {name:'GCD or HCF',lc:'https://leetcode.com/problems/find-greatest-common-divisor-of-array/',gfg:'https://practice.geeksforgeeks.org/problems/gcd-of-two-numbers3459/1'},
      {name:'Armstrong Numbers',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/armstrong-numbers2727/1'},
      {name:'Print all Divisors',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/sum-of-all-divisors-from-1-to-n4738/1'},
      {name:'Check for Prime',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/prime-number2314/1'},
    ]},
    {id:'s1-3',title:'1.3 · Learn STL / Collections',problems:[
      {name:'C++ STL (Pairs, Vectors, Maps, Sets)',lc:'N/A',gfg:'https://www.geeksforgeeks.org/the-c-standard-template-library-stl/'},
      {name:'Java Collections Framework',lc:'N/A',gfg:'https://www.geeksforgeeks.org/collections-in-java-2/'},
    ]},
    {id:'s1-4',title:'1.4 · Know Basic Maths',problems:[
      {name:'Count Digits in a Number',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/count-digits5716/1'},
      {name:'Reverse a Number',lc:'https://leetcode.com/problems/reverse-integer/',gfg:'https://practice.geeksforgeeks.org/problems/reverse-digits0316/1'},
      {name:'Check Palindrome Number',lc:'https://leetcode.com/problems/palindrome-number/',gfg:'https://practice.geeksforgeeks.org/problems/palindrome0746/1'},
      {name:'GCD / HCF of Two Numbers',lc:'https://leetcode.com/problems/find-greatest-common-divisor-of-array/',gfg:'https://practice.geeksforgeeks.org/problems/gcd-of-two-numbers3459/1'},
      {name:'Armstrong Numbers',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/armstrong-numbers2727/1'},
      {name:'Print all Divisors of a Number',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/sum-of-all-divisors-from-1-to-n4738/1'},
      {name:'Check for Prime Number',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/prime-number2314/1'},
    ]},
    {id:'s1-5',title:'1.5 · Learn Basic Recursion',problems:[
      {name:'Understand recursion — print something N times',lc:'N/A',gfg:'N/A'},
      {name:'Print 1 to N using Recursion',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/print-1-to-n-without-using-loops-1587115620/1'},
      {name:'Print N to 1 using Recursion',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/print-n-to-1-without-loop/1'},
      {name:'Sum of First N Numbers',lc:'N/A',gfg:'N/A'},
      {name:'Factorial of N Numbers',lc:'https://leetcode.com/problems/factorial-trailing-zeroes/',gfg:'https://practice.geeksforgeeks.org/problems/factorial5739/1'},
      {name:'Reverse an Array using Recursion',lc:'https://leetcode.com/problems/reverse-string/',gfg:'https://practice.geeksforgeeks.org/problems/reverse-an-array/0'},
      {name:'Check if String is Palindrome',lc:'https://leetcode.com/problems/valid-palindrome/',gfg:'https://practice.geeksforgeeks.org/problems/palindrome-string0817/1'},
      {name:'Fibonacci Number',lc:'https://leetcode.com/problems/fibonacci-number/',gfg:'https://practice.geeksforgeeks.org/problems/nth-fibonacci-number1335/1'},
    ]},
    {id:'s1-6',title:'1.6 · Learn Basic Hashing',problems:[
      {name:'Counting Frequencies of Array Elements',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/frequency-of-array-elements-1587115620/1'},
      {name:'Find the Highest/Lowest Frequency Element',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/find-the-highest-and-lowest-frequency-element/1'},
    ]},
  ]},
  {id:'s2',step:2,title:'Learn Important Sorting Techniques',color:'#d946ef',icon:'🔃',
  subsections:[
    {id:'s2-1',title:'2.1 · Sorting-I',problems:[
      {name:'Selection Sort',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/selection-sort/1'},
      {name:'Bubble Sort',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/bubble-sort/1'},
      {name:'Insertion Sort',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/insertion-sort/0'},
    ]},
    {id:'s2-2',title:'2.2 · Sorting-II',problems:[
      {name:'Merge Sort',lc:'https://leetcode.com/problems/sort-an-array/',gfg:'https://practice.geeksforgeeks.org/problems/merge-sort/1'},
      {name:'Quick Sort',lc:'https://leetcode.com/problems/sort-an-array/',gfg:'https://practice.geeksforgeeks.org/problems/quick-sort/1'},
      {name:'Recursive Bubble Sort',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/bubble-sort/1'},
      {name:'Recursive Insertion Sort',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/insertion-sort/0'},
    ]},
  ]},
  {id:'s3',step:3,title:'Solve Problems on Arrays [Easy → Hard]',color:'#f59e0b',icon:'📦',
  subsections:[
    {id:'s3-1',title:'3.1 · Easy',problems:[
      {name:'Largest Element in an Array',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/largest-element-in-array4009/1'},
      {name:'Second Largest Element',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/second-largest3735/1'},
      {name:'Check if Array is Sorted',lc:'https://leetcode.com/problems/check-if-array-is-sorted-and-rotated/',gfg:'https://practice.geeksforgeeks.org/problems/check-if-an-array-is-sorted0701/1'},
      {name:'Remove Duplicates from Sorted Array',lc:'https://leetcode.com/problems/remove-duplicates-from-sorted-array/',gfg:'https://practice.geeksforgeeks.org/problems/remove-duplicate-elements-from-sorted-array/1'},
      {name:'Left Rotate Array by One Place',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one2614/1'},
      {name:'Rotate Array by K Elements',lc:'https://leetcode.com/problems/rotate-array/',gfg:'https://practice.geeksforgeeks.org/problems/rotate-array-by-n-elements-1587115621/1'},
      {name:'Move Zeroes to End',lc:'https://leetcode.com/problems/move-zeroes/',gfg:'https://practice.geeksforgeeks.org/problems/move-all-zeroes-to-end-of-array0751/1'},
      {name:'Linear Search',lc:'https://leetcode.com/problems/find-target-indices-after-sorting-array/',gfg:'https://practice.geeksforgeeks.org/problems/who-will-win-1587115621/1'},
      {name:'Union of Two Sorted Arrays',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/union-of-two-sorted-arrays-1587115621/1'},
      {name:'Find Missing Number in Array',lc:'https://leetcode.com/problems/missing-number/',gfg:'https://practice.geeksforgeeks.org/problems/missing-number-in-array1416/1'},
      {name:'Max Consecutive Ones',lc:'https://leetcode.com/problems/max-consecutive-ones/',gfg:'https://practice.geeksforgeeks.org/problems/maximize-number-of-1s0905/1'},
      {name:'Find the number that appears once (XOR)',lc:'https://leetcode.com/problems/single-number/',gfg:'https://practice.geeksforgeeks.org/problems/element-appearing-once2552/1'},
      {name:'Longest Subarray with Sum K (Positives)',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/longest-sub-array-with-sum-k0809/1'},
      {name:'Longest Subarray with Sum K (Positives + Negatives)',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/longest-sub-array-with-sum-k0809/1'},
    ]},
    {id:'s3-2',title:'3.2 · Medium',problems:[
      {name:'2Sum Problem',lc:'https://leetcode.com/problems/two-sum/',gfg:'https://practice.geeksforgeeks.org/problems/key-pair5616/1'},
      {name:'Sort Array of 0s, 1s and 2s (Dutch Flag)',lc:'https://leetcode.com/problems/sort-colors/',gfg:'https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s4231/1'},
      {name:'Majority Element (>n/2)',lc:'https://leetcode.com/problems/majority-element/',gfg:'https://practice.geeksforgeeks.org/problems/majority-element-1587115620/1'},
      {name:"Maximum Subarray (Kadane's Algorithm)",lc:'https://leetcode.com/problems/maximum-subarray/',gfg:'https://practice.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1'},
      {name:'Maximum Product Subarray',lc:'https://leetcode.com/problems/maximum-product-subarray/',gfg:'https://practice.geeksforgeeks.org/problems/maximum-product-subarray3604/1'},
      {name:'Stock Buy and Sell',lc:'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',gfg:'https://practice.geeksforgeeks.org/problems/stock-buy-and-sell-1587115621/1'},
      {name:'Rearrange Array Alternately',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/rearrange-array-alternately-1587115620/1'},
      {name:'Next Permutation',lc:'https://leetcode.com/problems/next-permutation/',gfg:'https://practice.geeksforgeeks.org/problems/next-permutation5226/1'},
      {name:'Longest Consecutive Sequence',lc:'https://leetcode.com/problems/longest-consecutive-sequence/',gfg:'https://practice.geeksforgeeks.org/problems/longest-consecutive-subsequence2324/1'},
      {name:'Set Matrix Zeroes',lc:'https://leetcode.com/problems/set-matrix-zeroes/',gfg:'https://practice.geeksforgeeks.org/problems/a-boolean-matrix-question1437/1'},
      {name:'Rotate Matrix by 90 Degrees',lc:'https://leetcode.com/problems/rotate-image/',gfg:'https://practice.geeksforgeeks.org/problems/rotate-by-90-degree-1587115621/1'},
      {name:'Print Matrix in Spiral Order',lc:'https://leetcode.com/problems/spiral-matrix/',gfg:'https://practice.geeksforgeeks.org/problems/spirally-traversing-a-matrix-1587115621/1'},
      {name:'Count Subarrays with XOR = K',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/count-subarray-with-given-xor/1'},
    ]},
    {id:'s3-3',title:'3.3 · Hard',problems:[
      {name:'3Sum Problem',lc:'https://leetcode.com/problems/3sum/',gfg:'https://practice.geeksforgeeks.org/problems/triplet-sum-in-array-1587115621/1'},
      {name:'4Sum Problem',lc:'https://leetcode.com/problems/4sum/',gfg:'https://practice.geeksforgeeks.org/problems/find-all-four-sum-numbers1732/1'},
      {name:'Largest Subarray with 0 Sum',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1'},
      {name:'Count Subarrays with Given Sum',lc:'https://leetcode.com/problems/subarray-sum-equals-k/',gfg:'https://practice.geeksforgeeks.org/problems/subarray-with-given-sum-1587115621/1'},
      {name:'Count Inversions in Array (Merge Sort)',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/inversion-of-array-1587115620/1'},
      {name:'Reverse Pairs',lc:'https://leetcode.com/problems/reverse-pairs/',gfg:'https://practice.geeksforgeeks.org/problems/count-inversions/1'},
      {name:'Merge Overlapping Subintervals',lc:'https://leetcode.com/problems/merge-intervals/',gfg:'https://practice.geeksforgeeks.org/problems/overlapping-intervals--170633/1'},
      {name:'Merge Two Sorted Arrays without Extra Space',lc:'https://leetcode.com/problems/merge-sorted-array/',gfg:'https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays5135/1'},
      {name:'Find the Missing and Repeating Number',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/find-the-missing-and-repeating2512/1'},
      {name:'Majority Element II (>n/3)',lc:'https://leetcode.com/problems/majority-element-ii/',gfg:'https://practice.geeksforgeeks.org/problems/majority-vote/1'},
    ]},
  ]},
  {id:'s4',step:4,title:'Binary Search [1D Arrays, 2D Arrays, BS on Answers]',color:'#10b981',icon:'🔍',
  subsections:[
    {id:'s4-1',title:'4.1 · BS on 1D Arrays',problems:[
      {name:'Binary Search to find X in Sorted Array',lc:'https://leetcode.com/problems/binary-search/',gfg:'https://practice.geeksforgeeks.org/problems/binary-search-1587115620/1'},
      {name:'Implement Lower Bound',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/implement-lower-bound/1'},
      {name:'Implement Upper Bound',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/implement-upper-bound/1'},
      {name:'Search Insert Position',lc:'https://leetcode.com/problems/search-insert-position/',gfg:'https://practice.geeksforgeeks.org/problems/search-insert-position-of-k-in-a-sorted-array/1'},
      {name:'Floor / Ceil in Sorted Array',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/ceil-the-floor2802/1'},
      {name:'Find the First or Last Occurrence of a Given Number',lc:'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/',gfg:'https://practice.geeksforgeeks.org/problems/first-and-last-occurrences-of-x3116/1'},
      {name:'Count Occurrences in Sorted Array',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/number-of-occurrence2259/1'},
      {name:'Search in Rotated Sorted Array I',lc:'https://leetcode.com/problems/search-in-rotated-sorted-array/',gfg:'https://practice.geeksforgeeks.org/problems/search-in-a-rotated-array4618/1'},
      {name:'Search in Rotated Sorted Array II',lc:'https://leetcode.com/problems/search-in-rotated-sorted-array-ii/',gfg:'N/A'},
      {name:'Find Minimum in Rotated Sorted Array',lc:'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',gfg:'https://practice.geeksforgeeks.org/problems/minimum-element-in-a-sorted-and-rotated-array3611/1'},
      {name:'Find out how many times the array has been rotated',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/rotation4723/1'},
      {name:'Single Element in a Sorted Array',lc:'https://leetcode.com/problems/single-element-in-a-sorted-array/',gfg:'N/A'},
      {name:'Find Peak Element',lc:'https://leetcode.com/problems/find-peak-element/',gfg:'https://practice.geeksforgeeks.org/problems/peak-element/1'},
    ]},
    {id:'s4-2',title:'4.2 · BS on Answers',problems:[
      {name:'Find Square Root of a Number in log n',lc:'https://leetcode.com/problems/sqrtx/',gfg:'https://practice.geeksforgeeks.org/problems/square-root/0'},
      {name:'Find the Nth Root of a Number',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/find-nth-root-of-m5843/1'},
      {name:'Koko Eating Bananas',lc:'https://leetcode.com/problems/koko-eating-bananas/',gfg:'N/A'},
      {name:'Minimum Days to Make M Bouquets',lc:'https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/',gfg:'N/A'},
      {name:'Find the Smallest Divisor Given a Threshold',lc:'https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/',gfg:'N/A'},
      {name:'Capacity to Ship Packages within D Days',lc:'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/',gfg:'N/A'},
      {name:'Kth Missing Positive Number',lc:'https://leetcode.com/problems/kth-missing-positive-number/',gfg:'https://practice.geeksforgeeks.org/problems/k-th-missing-element3635/1'},
      {name:'Aggressive Cows',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/aggressive-cows/1'},
      {name:'Book Allocation',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1'},
      {name:'Split Array — Largest Sum',lc:'https://leetcode.com/problems/split-array-largest-sum/',gfg:'https://practice.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1'},
      {name:"Painter's Partition Problem",lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/the-painters-partition-problem1535/1'},
      {name:'Minimize Max Distance to Gas Station',lc:'https://leetcode.com/problems/minimize-max-distance-to-gas-station/',gfg:'N/A'},
      {name:'Median of Two Sorted Arrays',lc:'https://leetcode.com/problems/median-of-two-sorted-arrays/',gfg:'https://practice.geeksforgeeks.org/problems/median-of-two-sorted-arrays-of-different-sizes1215/1'},
      {name:'Kth Element of Two Sorted Arrays',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array1317/1'},
    ]},
    {id:'s4-3',title:'4.3 · BS on 2D Arrays',problems:[
      {name:'Find the Row with Maximum Number of 1s',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/row-with-max-1s0023/1'},
      {name:'Search in a 2D Matrix',lc:'https://leetcode.com/problems/search-a-2d-matrix/',gfg:'https://practice.geeksforgeeks.org/problems/search-in-a-matrix-1587115621/1'},
      {name:'Search in a 2D Matrix II',lc:'https://leetcode.com/problems/search-a-2d-matrix-ii/',gfg:'N/A'},
      {name:'Find Peak Element (2D)',lc:'https://leetcode.com/problems/find-a-peak-element-ii/',gfg:'N/A'},
      {name:'Matrix Median',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix1527/1'},
    ]},
  ]},
  {id:'s5',step:5,title:'Strings [Basic and Medium]',color:'#f43f5e',icon:'🔤',
  subsections:[
    {id:'s5-1',title:'5.1 · Basic and Easy String Problems',problems:[
      {name:'Remove Outermost Parentheses',lc:'https://leetcode.com/problems/remove-outermost-parentheses/',gfg:'https://practice.geeksforgeeks.org/problems/remove-outermost-parentheses/1'},
      {name:'Reverse Words in a String',lc:'https://leetcode.com/problems/reverse-words-in-a-string/',gfg:'https://practice.geeksforgeeks.org/problems/reverse-words-in-a-given-string5459/1'},
      {name:'Largest Odd Number in a String',lc:'https://leetcode.com/problems/largest-odd-number-in-string/',gfg:'N/A'},
      {name:'Longest Common Prefix',lc:'https://leetcode.com/problems/longest-common-prefix/',gfg:'https://practice.geeksforgeeks.org/problems/longest-common-prefix-in-an-array5129/1'},
      {name:'Isomorphic Strings',lc:'https://leetcode.com/problems/isomorphic-strings/',gfg:'https://practice.geeksforgeeks.org/problems/isomorphic-strings5219/1'},
      {name:'Check whether two strings are anagram',lc:'https://leetcode.com/problems/valid-anagram/',gfg:'https://practice.geeksforgeeks.org/problems/anagram-of-string/1'},
      {name:'Sort Characters by Frequency',lc:'https://leetcode.com/problems/sort-characters-by-frequency/',gfg:'N/A'},
      {name:'Maximum Nesting Depth of the Parentheses',lc:'https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/',gfg:'N/A'},
      {name:'Roman to Integer',lc:'https://leetcode.com/problems/roman-to-integer/',gfg:'https://practice.geeksforgeeks.org/problems/roman-number-to-integer3201/1'},
      {name:'Integer to Roman',lc:'https://leetcode.com/problems/integer-to-roman/',gfg:'N/A'},
      {name:'Implement Atoi',lc:'https://leetcode.com/problems/string-to-integer-atoi/',gfg:'https://practice.geeksforgeeks.org/problems/implement-atoi/1'},
      {name:'Longest Palindromic Substring',lc:'https://leetcode.com/problems/longest-palindromic-substring/',gfg:'https://practice.geeksforgeeks.org/problems/longest-palindrome-in-a-string3411/1'},
      {name:'Sum of Beauty of All Substrings',lc:'https://leetcode.com/problems/sum-of-beauty-of-all-substrings/',gfg:'N/A'},
    ]},
    {id:'s5-2',title:'5.2 · Medium String Problems',problems:[
      {name:'Find the Index of the First Occurrence in a String (KMP)',lc:'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/',gfg:'https://practice.geeksforgeeks.org/problems/index-of-first-occurrence5115/1'},
      {name:'Repeated String Match',lc:'https://leetcode.com/problems/repeated-string-match/',gfg:'N/A'},
      {name:'Count and Say',lc:'https://leetcode.com/problems/count-and-say/',gfg:'N/A'},
      {name:'Compare Version Numbers',lc:'https://leetcode.com/problems/compare-version-numbers/',gfg:'N/A'},
      {name:'Z-Function / Z-Algorithm',lc:'N/A',gfg:'N/A'},
      {name:'KMP Algorithm / LPS Array',lc:'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/',gfg:'https://practice.geeksforgeeks.org/problems/longest-prefix-suffix2527/1'},
      {name:'Minimum Characters to Make String Palindrome',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/minimum-characters-to-be-added-at-front-to-make-string-palindrome/1'},
    ]},
  ]},
  {id:'s6',step:6,title:'Learn LinkedList [Single LL, Double LL, Medium, Hard FAQs]',color:'#8b5cf6',icon:'🔗',
  subsections:[
    {id:'s6-1',title:'6.1 · Learn 1D LinkedList',problems:[
      {name:'Introduction to Linked List',lc:'N/A',gfg:'https://www.geeksforgeeks.org/data-structures/linked-list/'},
      {name:'Inserting a Node in LinkedList',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/linked-list-insertion-1587115620/1'},
      {name:'Deleting a Node in LinkedList',lc:'https://leetcode.com/problems/delete-node-in-a-linked-list/',gfg:'https://practice.geeksforgeeks.org/problems/node-at-a-given-index-in-linked-list/1'},
      {name:'Find the Length of a LinkedList',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/count-nodes-of-linked-list/1'},
      {name:'Search an Element in a LinkedList',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/search-in-linked-list-1664434193/1'},
    ]},
    {id:'s6-2',title:'6.2 · Learn Doubly LinkedList',problems:[
      {name:'Introduction to DLL, why we need DLL',lc:'N/A',gfg:'https://www.geeksforgeeks.org/doubly-linked-list/'},
      {name:'Insert a Node in DLL',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/insert-a-node-in-doubly-linked-list/1'},
      {name:'Delete a Node in DLL',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/delete-node-in-doubly-linked-list/1'},
      {name:'Reverse a DLL',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/reverse-a-doubly-linked-list/1'},
    ]},
    {id:'s6-3',title:'6.3 · Medium Problems of LL',problems:[
      {name:'Middle of the Linked List',lc:'https://leetcode.com/problems/middle-of-the-linked-list/',gfg:'https://practice.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1'},
      {name:'Reverse a LinkedList',lc:'https://leetcode.com/problems/reverse-linked-list/',gfg:'https://practice.geeksforgeeks.org/problems/reverse-a-linked-list/1'},
      {name:'Reverse LL in Groups of Size K',lc:'https://leetcode.com/problems/reverse-nodes-in-k-group/',gfg:'https://practice.geeksforgeeks.org/problems/reverse-a-linked-list-in-groups-of-given-size1805/1'},
      {name:'Detect a Loop / Cycle in LL',lc:'https://leetcode.com/problems/linked-list-cycle/',gfg:'https://practice.geeksforgeeks.org/problems/detect-loop-in-linked-list/1'},
      {name:'Find the Starting Point of Loop in LL',lc:'https://leetcode.com/problems/linked-list-cycle-ii/',gfg:'https://practice.geeksforgeeks.org/problems/find-the-first-node-of-loop-in-linked-list/1'},
      {name:'Length of Loop in LL',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/find-length-of-loop/1'},
      {name:'Check if LL is Palindrome or not',lc:'https://leetcode.com/problems/palindrome-linked-list/',gfg:'https://practice.geeksforgeeks.org/problems/check-if-linked-list-is-pallindrome/1'},
      {name:'Segregate Odd and Even Nodes in LL',lc:'https://leetcode.com/problems/odd-even-linked-list/',gfg:'https://practice.geeksforgeeks.org/problems/segregate-even-and-odd-nodes-in-a-linked-list5035/1'},
      {name:'Remove Nth Node from the Back of LL',lc:'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',gfg:'https://practice.geeksforgeeks.org/problems/nth-node-from-end-of-linked-list/1'},
      {name:'Delete the Middle Node of LL',lc:'https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/',gfg:'N/A'},
      {name:'Sort LL',lc:'https://leetcode.com/problems/sort-list/',gfg:'https://practice.geeksforgeeks.org/problems/sort-a-linked-list/1'},
      {name:'Find the Intersection Point of Y LL',lc:'https://leetcode.com/problems/intersection-of-two-linked-lists/',gfg:'https://practice.geeksforgeeks.org/problems/intersection-point-in-y-shapped-linked-lists/1'},
      {name:'Add 1 to a Number Represented as LL',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/add-1-to-a-number-represented-as-linked-list/1'},
      {name:'Add Two Numbers in LL',lc:'https://leetcode.com/problems/add-two-numbers/',gfg:'https://practice.geeksforgeeks.org/problems/add-two-numbers-represented-by-linked-lists/1'},
    ]},
    {id:'s6-4',title:'6.4 · Hard Problems of LL',problems:[
      {name:'Rotate a LL',lc:'https://leetcode.com/problems/rotate-list/',gfg:'https://practice.geeksforgeeks.org/problems/rotate-a-linked-list/1'},
      {name:'Flattening a Linked List',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1'},
      {name:'Copy List with Random Pointer',lc:'https://leetcode.com/problems/copy-list-with-random-pointer/',gfg:'https://practice.geeksforgeeks.org/problems/clone-a-linked-list-with-next-and-random-pointer/1'},
    ]},
    {id:'s6-5',title:'6.5 · Doubly LinkedList — Medium/Hard',problems:[
      {name:'Design Browser History',lc:'https://leetcode.com/problems/design-browser-history/',gfg:'N/A'},
      {name:'LRU Cache',lc:'https://leetcode.com/problems/lru-cache/',gfg:'https://practice.geeksforgeeks.org/problems/lru-cache/1'},
      {name:'LFU Cache',lc:'https://leetcode.com/problems/lfu-cache/',gfg:'N/A'},
      {name:'Find Pairs with Given Sum in DLL',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/find-pairs-with-given-sum-in-doubly-linked-list/1'},
      {name:'Remove Duplicates from Sorted DLL',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/remove-duplicates-from-a-sorted-doubly-linked-list/1'},
    ]},
  ]},
  {id:'s7',step:7,title:'Recursion [Pattern Wise]',color:'#06b6d4',icon:'🔄',
  subsections:[
    {id:'s7-1',title:'7.1 · Get a Strong Hold',problems:[
      {name:'Recursive Implementation of atoi()',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/recursive-implementation-of-atoi2559/1'},
      {name:'Pow(x, n)',lc:'https://leetcode.com/problems/powx-n/',gfg:'https://practice.geeksforgeeks.org/problems/power-of-numbers/0'},
      {name:'Count Good Numbers',lc:'https://leetcode.com/problems/count-good-numbers/',gfg:'N/A'},
      {name:'Sort a Stack using Recursion',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/sort-a-stack/1'},
      {name:'Reverse a Stack using Recursion',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/reverse-a-stack/1'},
      {name:'Delete Middle Element of a Stack',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/delete-middle-element-of-a-stack/1'},
    ]},
    {id:'s7-2',title:'7.2 · Subsequences Pattern',problems:[
      {name:'Generate All Binary Strings',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/generate-all-binary-strings/1'},
      {name:'Generate Parentheses',lc:'https://leetcode.com/problems/generate-parentheses/',gfg:'https://practice.geeksforgeeks.org/problems/generate-all-possible-parentheses/1'},
      {name:'Print all Subsequences / Power Set',lc:'https://leetcode.com/problems/subsets/',gfg:'https://practice.geeksforgeeks.org/problems/power-set4302/1'},
      {name:'Combination Sum',lc:'https://leetcode.com/problems/combination-sum/',gfg:'https://practice.geeksforgeeks.org/problems/combination-sum-part-2/1'},
      {name:'Combination Sum II',lc:'https://leetcode.com/problems/combination-sum-ii/',gfg:'https://practice.geeksforgeeks.org/problems/combination-sum-part-2/1'},
      {name:'Subset Sum I',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/subset-sums2234/1'},
      {name:'Subset Sum II (No Duplicates)',lc:'https://leetcode.com/problems/subsets-ii/',gfg:'N/A'},
      {name:'Combination Sum III',lc:'https://leetcode.com/problems/combination-sum-iii/',gfg:'N/A'},
      {name:'Letter Combinations of a Phone Number',lc:'https://leetcode.com/problems/letter-combinations-of-a-phone-number/',gfg:'https://practice.geeksforgeeks.org/problems/mobile-numeric-keypad5456/1'},
    ]},
    {id:'s7-3',title:'7.3 · Trying out all Combos / Hard',problems:[
      {name:'Permutation Sequence',lc:'https://leetcode.com/problems/permutation-sequence/',gfg:'N/A'},
      {name:'Print all Permutations of a String/Array',lc:'https://leetcode.com/problems/permutations/',gfg:'https://practice.geeksforgeeks.org/problems/permutations-of-a-given-string2041/1'},
      {name:'N Queens',lc:'https://leetcode.com/problems/n-queens/',gfg:'https://practice.geeksforgeeks.org/problems/n-queen-problem0315/1'},
      {name:'Sudoku Solver',lc:'https://leetcode.com/problems/sudoku-solver/',gfg:'https://practice.geeksforgeeks.org/problems/solve-the-sudoku-1587115621/1'},
      {name:'M-Coloring Problem',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1'},
      {name:'Rat in a Maze',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1'},
      {name:'Word Break II (Print all ways)',lc:'https://leetcode.com/problems/word-break-ii/',gfg:'https://practice.geeksforgeeks.org/problems/word-break-part-23249/1'},
    ]},
  ]},
  {id:'s8',step:8,title:'Bit Manipulation [Concepts & Problems]',color:'#f97316',icon:'⚙️',
  subsections:[
    {id:'s8-1',title:'8.1 · Learn Bit Manipulation',problems:[
      {name:'Introduction to Bit Manipulation [Theory]',lc:'N/A',gfg:'https://www.geeksforgeeks.org/bits-manipulation-important-tactics/'},
      {name:'Check if the i-th bit is set or not',lc:'N/A',gfg:'N/A'},
      {name:'Check if a number is Power of 2',lc:'https://leetcode.com/problems/power-of-two/',gfg:'https://practice.geeksforgeeks.org/problems/power-of-2/0'},
      {name:'Count the Number of Set Bits',lc:'https://leetcode.com/problems/number-of-1-bits/',gfg:'https://practice.geeksforgeeks.org/problems/set-bits0143/1'},
      {name:'Divide Two Integers without Division Operator',lc:'https://leetcode.com/problems/divide-two-integers/',gfg:'N/A'},
    ]},
    {id:'s8-2',title:'8.2 · Interview Problems',problems:[
      {name:'Count Number of Bits to Flip to Convert A to B',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/bit-difference-1587115620/1'},
      {name:'Find the Number that Appears Odd Number of Times',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/find-the-odd-occuring-element/1'},
      {name:'Power Set',lc:'https://leetcode.com/problems/subsets/',gfg:'https://practice.geeksforgeeks.org/problems/power-set4302/1'},
      {name:'Find XOR of Numbers from L to R',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/find-xor-of-numbers-from-l-to-r/1'},
      {name:'Find Two Numbers Appearing Odd Number of Times',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/two-numbers-with-odd-occurrences5150/1'},
    ]},
    {id:'s8-3',title:'8.3 · Advanced Maths',problems:[
      {name:'Print Prime Factors of a Number',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/prime-factors5052/1'},
      {name:'Sieve of Eratosthenes',lc:'https://leetcode.com/problems/count-primes/',gfg:'https://practice.geeksforgeeks.org/problems/sieve-of-eratosthenes5242/1'},
      {name:'Power(n, m) mod p',lc:'https://leetcode.com/problems/powx-n/',gfg:'https://practice.geeksforgeeks.org/problems/power-of-numbers/0'},
    ]},
  ]},
  {id:'s9',step:9,title:'Stack and Queues [Learning, Monotonic Stack, Implementation]',color:'#ec4899',icon:'📚',
  subsections:[
    {id:'s9-1',title:'9.1 · Learn Stack and Queue',problems:[
      {name:'Implement Stack using Arrays',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/implement-stack-using-array/1'},
      {name:'Implement Queue using Arrays',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/implement-queue-using-array/1'},
      {name:'Implement Stack using Queue',lc:'https://leetcode.com/problems/implement-stack-using-queues/',gfg:'https://practice.geeksforgeeks.org/problems/stack-using-two-queues/1'},
      {name:'Implement Queue using Stack',lc:'https://leetcode.com/problems/implement-queue-using-stacks/',gfg:'https://practice.geeksforgeeks.org/problems/queue-using-two-stacks/1'},
      {name:'Check for Balanced Parentheses',lc:'https://leetcode.com/problems/valid-parentheses/',gfg:'https://practice.geeksforgeeks.org/problems/parenthesis-checker2744/1'},
      {name:'Min Stack',lc:'https://leetcode.com/problems/min-stack/',gfg:'https://practice.geeksforgeeks.org/problems/special-stack/1'},
    ]},
    {id:'s9-2',title:'9.2 · Prefix, Infix, PostFix Conversion',problems:[
      {name:'Infix to Postfix Conversion using Stack',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/infix-to-postfix-1587115620/1'},
      {name:'Prefix to Infix Conversion',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/prefix-to-infix-conversion/1'},
      {name:'Postfix to Prefix Conversion',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/postfix-to-prefix-conversion/1'},
    ]},
    {id:'s9-3',title:'9.3 · Monotonic Stack / Queue Problems [VVV. Important]',problems:[
      {name:'Next Greater Element I',lc:'https://leetcode.com/problems/next-greater-element-i/',gfg:'https://practice.geeksforgeeks.org/problems/next-larger-element-1587115620/1'},
      {name:'Next Greater Element II',lc:'https://leetcode.com/problems/next-greater-element-ii/',gfg:'N/A'},
      {name:'Next Smaller Element',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/next-smaller-element/1'},
      {name:'Trapping Rain Water',lc:'https://leetcode.com/problems/trapping-rain-water/',gfg:'https://practice.geeksforgeeks.org/problems/trapping-rain-water-1587115621/1'},
      {name:'Sum of Subarray Minimums',lc:'https://leetcode.com/problems/sum-of-subarray-minimums/',gfg:'N/A'},
      {name:'Asteroid Collision',lc:'https://leetcode.com/problems/asteroid-collision/',gfg:'N/A'},
      {name:'Remove K Digits',lc:'https://leetcode.com/problems/remove-k-digits/',gfg:'N/A'},
      {name:'Largest Rectangle in Histogram',lc:'https://leetcode.com/problems/largest-rectangle-in-histogram/',gfg:'https://practice.geeksforgeeks.org/problems/maximum-rectangular-area-in-a-histogram-1587115620/1'},
      {name:'Maximal Rectangle',lc:'https://leetcode.com/problems/maximal-rectangle/',gfg:'https://practice.geeksforgeeks.org/problems/max-rectangle/1'},
    ]},
    {id:'s9-4',title:'9.4 · Implementation Problems',problems:[
      {name:'Sliding Window Maximum',lc:'https://leetcode.com/problems/sliding-window-maximum/',gfg:'https://practice.geeksforgeeks.org/problems/maximum-of-all-subarrays-of-size-k3101/1'},
      {name:'Stock Span Problem',lc:'https://leetcode.com/problems/online-stock-span/',gfg:'https://practice.geeksforgeeks.org/problems/stock-span-problem-1587115621/1'},
      {name:'The Celebrity Problem',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/the-celebrity-problem/1'},
      {name:'Rotten Oranges (BFS)',lc:'https://leetcode.com/problems/rotting-oranges/',gfg:'https://practice.geeksforgeeks.org/problems/rotten-oranges2536/1'},
      {name:'Decode the String',lc:'https://leetcode.com/problems/decode-string/',gfg:'N/A'},
    ]},
  ]},
  {id:'s10',step:10,title:'Sliding Window & Two Pointer Combined Problems',color:'#84cc16',icon:'🪟',
  subsections:[
    {id:'s10-1',title:'10.1 · Medium Problems',problems:[
      {name:'Longest Substring Without Repeating Characters',lc:'https://leetcode.com/problems/longest-substring-without-repeating-characters/',gfg:'https://practice.geeksforgeeks.org/problems/length-of-the-longest-substring3036/1'},
      {name:'Max Consecutive Ones III',lc:'https://leetcode.com/problems/max-consecutive-ones-iii/',gfg:'N/A'},
      {name:'Fruit Into Baskets',lc:'https://leetcode.com/problems/fruit-into-baskets/',gfg:'N/A'},
      {name:'Longest Repeating Character Replacement',lc:'https://leetcode.com/problems/longest-repeating-character-replacement/',gfg:'N/A'},
      {name:'Binary Subarray with Sum',lc:'https://leetcode.com/problems/binary-subarrays-with-sum/',gfg:'N/A'},
      {name:'Count Number of Nice Subarrays',lc:'https://leetcode.com/problems/count-number-of-nice-subarrays/',gfg:'N/A'},
      {name:'Number of Substrings Containing All Three Characters',lc:'https://leetcode.com/problems/number-of-substrings-containing-all-three-characters/',gfg:'N/A'},
      {name:'Maximum Points You Can Obtain from Cards',lc:'https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/',gfg:'N/A'},
    ]},
    {id:'s10-2',title:'10.2 · Hard Problems',problems:[
      {name:'Minimum Window Substring',lc:'https://leetcode.com/problems/minimum-window-substring/',gfg:'https://practice.geeksforgeeks.org/problems/smallest-window-in-a-string-containing-all-the-characters-of-another-string-1587115621/1'},
      {name:'Subarrays with K Different Integers',lc:'https://leetcode.com/problems/subarrays-with-k-different-integers/',gfg:'N/A'},
      {name:'Substring with Concatenation of All Words',lc:'https://leetcode.com/problems/substring-with-concatenation-of-all-words/',gfg:'N/A'},
    ]},
  ]},
  {id:'s11',step:11,title:'Heaps [Learning, Medium, Hard Problems]',color:'#0ea5e9',icon:'⛰️',
  subsections:[
    {id:'s11-1',title:'11.1 · Learn Heaps',problems:[
      {name:'Introduction to Heaps',lc:'N/A',gfg:'https://www.geeksforgeeks.org/binary-heap/'},
      {name:'Min Heap and Max Heap Implementation',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/operations-on-binary-min-heap/1'},
    ]},
    {id:'s11-2',title:'11.2 · Medium Problems',problems:[
      {name:'Kth Largest Element in an Array',lc:'https://leetcode.com/problems/kth-largest-element-in-an-array/',gfg:'https://practice.geeksforgeeks.org/problems/kth-largest-element-in-a-stream2220/1'},
      {name:'Kth Smallest Element in an Array',lc:'https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/',gfg:'https://practice.geeksforgeeks.org/problems/kth-smallest-element5635/1'},
      {name:'Merge M Sorted Lists',lc:'https://leetcode.com/problems/merge-k-sorted-lists/',gfg:'https://practice.geeksforgeeks.org/problems/merge-k-sorted-arrays/1'},
      {name:'Task Scheduler',lc:'https://leetcode.com/problems/task-scheduler/',gfg:'N/A'},
      {name:'Hands of Straights',lc:'https://leetcode.com/problems/hand-of-straights/',gfg:'N/A'},
    ]},
    {id:'s11-3',title:'11.3 · Hard Problems',problems:[
      {name:'Design Twitter',lc:'https://leetcode.com/problems/design-twitter/',gfg:'N/A'},
      {name:'Connect n Ropes with Minimum Cost',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/minimum-cost-of-ropes-1587115620/1'},
      {name:'Kth Largest Element in a Stream',lc:'https://leetcode.com/problems/kth-largest-element-in-a-stream/',gfg:'N/A'},
      {name:'Find Median from a Data Stream',lc:'https://leetcode.com/problems/find-median-from-data-stream/',gfg:'https://practice.geeksforgeeks.org/problems/find-median-in-a-stream-1587115620/1'},
      {name:'K Most Frequent Elements',lc:'https://leetcode.com/problems/top-k-frequent-elements/',gfg:'N/A'},
    ]},
  ]},
  {id:'s12',step:12,title:'Greedy Algorithms [Easy, Medium/Hard]',color:'#a3e635',icon:'💰',
  subsections:[
    {id:'s12-1',title:'12.1 · Easy Problems',problems:[
      {name:'Assign Cookies',lc:'https://leetcode.com/problems/assign-cookies/',gfg:'N/A'},
      {name:'Fractional Knapsack',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1'},
      {name:'Lemonade Change',lc:'https://leetcode.com/problems/lemonade-change/',gfg:'N/A'},
      {name:'Valid Parenthesis String',lc:'https://leetcode.com/problems/valid-parenthesis-string/',gfg:'N/A'},
    ]},
    {id:'s12-2',title:'12.2 · Medium/Hard',problems:[
      {name:'N Meetings in One Room',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1'},
      {name:'Jump Game',lc:'https://leetcode.com/problems/jump-game/',gfg:'https://practice.geeksforgeeks.org/problems/jump-game/1'},
      {name:'Jump Game II',lc:'https://leetcode.com/problems/jump-game-ii/',gfg:'N/A'},
      {name:'Job Sequencing Problem',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1'},
      {name:'Candy',lc:'https://leetcode.com/problems/candy/',gfg:'N/A'},
      {name:'Insert Interval',lc:'https://leetcode.com/problems/insert-interval/',gfg:'N/A'},
      {name:'Non-overlapping Intervals',lc:'https://leetcode.com/problems/non-overlapping-intervals/',gfg:'N/A'},
    ]},
  ]},
  {id:'s13',step:13,title:'Binary Trees [Traversals, Medium, Hard]',color:'#14b8a6',icon:'🌳',
  subsections:[
    {id:'s13-1',title:'13.1 · Traversals',problems:[
      {name:'Introduction to Trees',lc:'N/A',gfg:'https://www.geeksforgeeks.org/introduction-to-tree-data-structure-and-algorithm-tutorials/'},
      {name:'Binary Tree Traversal (Pre, In, Post)',lc:'https://leetcode.com/problems/binary-tree-inorder-traversal/',gfg:'https://practice.geeksforgeeks.org/problems/inorder-traversal/1'},
      {name:'Preorder Traversal',lc:'https://leetcode.com/problems/binary-tree-preorder-traversal/',gfg:'https://practice.geeksforgeeks.org/problems/preorder-traversal/1'},
      {name:'Postorder Traversal',lc:'https://leetcode.com/problems/binary-tree-postorder-traversal/',gfg:'https://practice.geeksforgeeks.org/problems/postorder-traversal/1'},
      {name:'Level Order Traversal',lc:'https://leetcode.com/problems/binary-tree-level-order-traversal/',gfg:'https://practice.geeksforgeeks.org/problems/level-order-traversal/1'},
      {name:'Iterative Preorder Traversal',lc:'https://leetcode.com/problems/binary-tree-preorder-traversal/',gfg:'N/A'},
      {name:'Iterative Inorder Traversal',lc:'https://leetcode.com/problems/binary-tree-inorder-traversal/',gfg:'N/A'},
      {name:'Iterative Postorder Traversal',lc:'https://leetcode.com/problems/binary-tree-postorder-traversal/',gfg:'N/A'},
    ]},
    {id:'s13-2',title:'13.2 · Medium Problems',problems:[
      {name:'Height of a Binary Tree',lc:'https://leetcode.com/problems/maximum-depth-of-binary-tree/',gfg:'https://practice.geeksforgeeks.org/problems/height-of-binary-tree/1'},
      {name:'Check if BT is Balanced or not',lc:'https://leetcode.com/problems/balanced-binary-tree/',gfg:'https://practice.geeksforgeeks.org/problems/check-for-balanced-tree/1'},
      {name:'Diameter of Binary Tree',lc:'https://leetcode.com/problems/diameter-of-binary-tree/',gfg:'https://practice.geeksforgeeks.org/problems/diameter-of-binary-tree/1'},
      {name:'Maximum Path Sum',lc:'https://leetcode.com/problems/binary-tree-maximum-path-sum/',gfg:'https://practice.geeksforgeeks.org/problems/maximum-path-sum-from-any-node/1'},
      {name:'Check if Two Trees are Identical',lc:'https://leetcode.com/problems/same-tree/',gfg:'N/A'},
      {name:'Zigzag Traversal of Binary Tree',lc:'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/',gfg:'https://practice.geeksforgeeks.org/problems/zigzag-tree-traversal/1'},
      {name:'Boundary Traversal of Binary Tree',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1'},
      {name:'Vertical Order Traversal of BT',lc:'https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/',gfg:'N/A'},
      {name:'Top View of Binary Tree',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/top-view-of-binary-tree/1'},
      {name:'Bottom View of Binary Tree',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1'},
      {name:'Right/Left View of Binary Tree',lc:'https://leetcode.com/problems/binary-tree-right-side-view/',gfg:'https://practice.geeksforgeeks.org/problems/right-view-of-binary-tree/1'},
      {name:'Symmetric Binary Tree',lc:'https://leetcode.com/problems/symmetric-tree/',gfg:'N/A'},
    ]},
    {id:'s13-3',title:'13.3 · Hard Problems',problems:[
      {name:'Root to Node Path in Binary Tree',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/root-to-leaf-paths/1'},
      {name:'LCA in Binary Tree',lc:'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/',gfg:'https://practice.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-binary-tree/1'},
      {name:'Maximum Width of Binary Tree',lc:'https://leetcode.com/problems/maximum-width-of-binary-tree/',gfg:'N/A'},
      {name:'Print all Nodes at Distance K',lc:'https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/',gfg:'N/A'},
      {name:'Minimum Time to Burn the Binary Tree from a Node',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/burning-tree/1'},
      {name:'Count Total Nodes in a Complete Binary Tree',lc:'https://leetcode.com/problems/count-complete-tree-nodes/',gfg:'N/A'},
      {name:'Construct BT from Preorder and Inorder',lc:'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',gfg:'https://practice.geeksforgeeks.org/problems/construct-tree-1/1'},
      {name:'Construct BT from Postorder and Inorder',lc:'https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/',gfg:'N/A'},
      {name:'Serialize and De-serialize Binary Tree',lc:'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',gfg:'N/A'},
      {name:'Flatten Binary Tree to LinkedList',lc:'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/',gfg:'N/A'},
    ]},
  ]},
  {id:'s14',step:14,title:'Binary Search Trees [Concept and Problems]',color:'#f59e0b',icon:'🔢',
  subsections:[
    {id:'s14-1',title:'14.1 · Concepts',problems:[
      {name:'Introduction to BST',lc:'N/A',gfg:'https://www.geeksforgeeks.org/binary-search-tree-data-structure/'},
      {name:'Search in a BST',lc:'https://leetcode.com/problems/search-in-a-binary-search-tree/',gfg:'N/A'},
      {name:'Find Min/Max in BST',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/minimum-element-in-bst/1'},
    ]},
    {id:'s14-2',title:'14.2 · Practice Problems',problems:[
      {name:'Ceil in a BST',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/implementing-ceil-in-bst/1'},
      {name:'Floor in a BST',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/floor-in-bst/1'},
      {name:'Insert a Node in BST',lc:'https://leetcode.com/problems/insert-into-a-binary-search-tree/',gfg:'N/A'},
      {name:'Delete a Node in BST',lc:'https://leetcode.com/problems/delete-node-in-a-bst/',gfg:'N/A'},
      {name:'Kth Smallest Element in BST',lc:'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',gfg:'https://practice.geeksforgeeks.org/problems/kth-smallest-element-in-bst/1'},
      {name:'Validate BST',lc:'https://leetcode.com/problems/validate-binary-search-tree/',gfg:'https://practice.geeksforgeeks.org/problems/check-for-bst/1'},
      {name:'LCA in BST',lc:'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',gfg:'N/A'},
      {name:'Construct BST from Preorder Traversal',lc:'https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/',gfg:'N/A'},
      {name:'Inorder Successor / Predecessor in BST',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/predecessor-and-successor/1'},
      {name:'BST Iterator',lc:'https://leetcode.com/problems/binary-search-tree-iterator/',gfg:'N/A'},
      {name:'Two Sum in BST',lc:'https://leetcode.com/problems/two-sum-iv-input-is-a-bst/',gfg:'N/A'},
      {name:'Recover BST (Two Nodes Swapped)',lc:'https://leetcode.com/problems/recover-binary-search-tree/',gfg:'N/A'},
      {name:'Largest BST in Binary Tree',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/largest-bst/1'},
    ]},
  ]},
  {id:'s15',step:15,title:'Graphs [BFS, DFS, Topo Sort, Shortest Path, MST, Bridges]',color:'#6366f1',icon:'🕸️',
  subsections:[
    {id:'s15-1',title:'15.1 · Learning',problems:[
      {name:'Graph and Types',lc:'N/A',gfg:'https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/'},
      {name:'Breadth First Search (BFS)',lc:'https://leetcode.com/problems/number-of-islands/',gfg:'https://practice.geeksforgeeks.org/problems/bfs-traversal-of-graph/1'},
      {name:'Depth First Search (DFS)',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1'},
      {name:'Number of Provinces',lc:'https://leetcode.com/problems/number-of-provinces/',gfg:'N/A'},
      {name:'Rotten Oranges',lc:'https://leetcode.com/problems/rotting-oranges/',gfg:'https://practice.geeksforgeeks.org/problems/rotten-oranges2536/1'},
      {name:'Flood Fill',lc:'https://leetcode.com/problems/flood-fill/',gfg:'N/A'},
      {name:'Cycle Detection in Undirected Graph (BFS)',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1'},
      {name:'Cycle Detection in Undirected Graph (DFS)',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1'},
      {name:'0/1 Matrix — Distance of Nearest 0',lc:'https://leetcode.com/problems/01-matrix/',gfg:'N/A'},
      {name:'Surrounded Regions',lc:'https://leetcode.com/problems/surrounded-regions/',gfg:'N/A'},
      {name:'Number of Enclaves',lc:'https://leetcode.com/problems/number-of-enclaves/',gfg:'N/A'},
      {name:'Word Ladder I',lc:'https://leetcode.com/problems/word-ladder/',gfg:'https://practice.geeksforgeeks.org/problems/word-ladder/1'},
      {name:'Word Ladder II',lc:'https://leetcode.com/problems/word-ladder-ii/',gfg:'N/A'},
      {name:'Bipartite Graph (BFS)',lc:'https://leetcode.com/problems/is-graph-bipartite/',gfg:'https://practice.geeksforgeeks.org/problems/bipartite-graph/1'},
      {name:'Cycle Detection in Directed Graph (DFS)',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/detect-cycle-in-a-directed-graph/1'},
    ]},
    {id:'s15-2',title:'15.2 · Topo Sort & Problems',problems:[
      {name:'Topological Sort (DFS)',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/topological-sort/1'},
      {name:"Kahn's Algorithm (BFS Topo Sort)",lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/topological-sort/1'},
      {name:'Course Schedule I',lc:'https://leetcode.com/problems/course-schedule/',gfg:'N/A'},
      {name:'Course Schedule II',lc:'https://leetcode.com/problems/course-schedule-ii/',gfg:'N/A'},
      {name:'Find Eventual Safe States',lc:'https://leetcode.com/problems/find-eventual-safe-states/',gfg:'N/A'},
      {name:'Alien Dictionary',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/alien-dictionary/1'},
    ]},
    {id:'s15-3',title:'15.3 · Shortest Path Algorithms',problems:[
      {name:"Dijkstra's Algorithm",lc:'https://leetcode.com/problems/network-delay-time/',gfg:'https://practice.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1'},
      {name:'Bellman-Ford Algorithm',lc:'https://leetcode.com/problems/cheapest-flights-within-k-stops/',gfg:'https://practice.geeksforgeeks.org/problems/distance-from-the-source-bellman-ford-algorithm/1'},
      {name:'Floyd Warshall Algorithm',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/implementing-floyd-warshall2042/1'},
      {name:'Path with Minimum Effort',lc:'https://leetcode.com/problems/path-with-minimum-effort/',gfg:'N/A'},
      {name:'Cheapest Flights within K Stops',lc:'https://leetcode.com/problems/cheapest-flights-within-k-stops/',gfg:'N/A'},
      {name:'Network Delay Time',lc:'https://leetcode.com/problems/network-delay-time/',gfg:'N/A'},
      {name:'Number of Ways to Arrive at Destination',lc:'https://leetcode.com/problems/number-of-ways-to-arrive-at-destination/',gfg:'N/A'},
      {name:'Accounts Merge',lc:'https://leetcode.com/problems/accounts-merge/',gfg:'N/A'},
    ]},
    {id:'s15-4',title:'15.4 · MST / Disjoint Set',problems:[
      {name:"Prim's Minimum Spanning Tree Algorithm",lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/minimum-spanning-tree/1'},
      {name:'Disjoint Set (Union-Find)',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/union-find/1'},
      {name:"Kruskal's Algorithm",lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/minimum-spanning-tree/1'},
      {name:'Number of Operations to Make Network Connected',lc:'https://leetcode.com/problems/number-of-operations-to-make-network-connected/',gfg:'N/A'},
      {name:'Most Stones Removed with Same Row or Column',lc:'https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/',gfg:'N/A'},
      {name:'Making a Large Island',lc:'https://leetcode.com/problems/making-a-large-island/',gfg:'N/A'},
    ]},
    {id:'s15-5',title:'15.5 · Other Algorithms',problems:[
      {name:'Bridges in Graph',lc:'https://leetcode.com/problems/critical-connections-in-a-network/',gfg:'N/A'},
      {name:'Articulation Points',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/articulation-point-1/1'},
      {name:"Kosaraju's Algorithm (SCC)",lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/strongly-connected-components-kosarajus-algo/1'},
    ]},
  ]},
  {id:'s16',step:16,title:'Dynamic Programming [Patterns & Problems]',color:'#ec4899',icon:'🧩',
  subsections:[
    {id:'s16-1',title:'16.1 · Introduction to DP',problems:[
      {name:'Introduction to Dynamic Programming',lc:'N/A',gfg:'https://www.geeksforgeeks.org/dynamic-programming/'},
      {name:'Climbing Stairs',lc:'https://leetcode.com/problems/climbing-stairs/',gfg:'https://practice.geeksforgeeks.org/problems/count-ways-to-reach-the-nth-stair-1587115620/1'},
      {name:'Frog Jump (Tabulation)',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/minimal-cost/1'},
      {name:'Maximum Sum of Non-Adjacent Elements (House Robber)',lc:'https://leetcode.com/problems/house-robber/',gfg:'N/A'},
      {name:'House Robber II',lc:'https://leetcode.com/problems/house-robber-ii/',gfg:'N/A'},
    ]},
    {id:'s16-2',title:'16.2 · 2D/3D DP and DP on Grids',problems:[
      {name:'Grid Unique Paths',lc:'https://leetcode.com/problems/unique-paths/',gfg:'N/A'},
      {name:'Grid Unique Paths II (with Obstacles)',lc:'https://leetcode.com/problems/unique-paths-ii/',gfg:'N/A'},
      {name:'Minimum Path Sum in Grid',lc:'https://leetcode.com/problems/minimum-path-sum/',gfg:'N/A'},
      {name:'Minimum Path Sum in Triangular Grid',lc:'https://leetcode.com/problems/triangle/',gfg:'N/A'},
      {name:'Minimum/Maximum Falling Path Sum',lc:'https://leetcode.com/problems/minimum-falling-path-sum/',gfg:'N/A'},
      {name:'Cherry Pickup II (3D DP)',lc:'https://leetcode.com/problems/cherry-pickup-ii/',gfg:'N/A'},
    ]},
    {id:'s16-3',title:'16.3 · DP on Subsequences',problems:[
      {name:'Subset Sum Equal to Target',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/subset-sum-problem-1611555638/1'},
      {name:'Partition Equal Subset Sum',lc:'https://leetcode.com/problems/partition-equal-subset-sum/',gfg:'N/A'},
      {name:'Count Subsets with Sum K',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/perfect-sum-problem5633/1'},
      {name:'0/1 Knapsack',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/0-1-knapsack-problem/0'},
      {name:'Coin Change (Minimum Coins)',lc:'https://leetcode.com/problems/coin-change/',gfg:'N/A'},
      {name:'Coin Change II (Number of Ways)',lc:'https://leetcode.com/problems/coin-change-ii/',gfg:'N/A'},
      {name:'Unbounded Knapsack',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/knapsack-with-duplicate-items4201/1'},
      {name:'Rod Cutting Problem',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/rod-cutting0840/1'},
    ]},
    {id:'s16-4',title:'16.4 · DP on Strings',problems:[
      {name:'Longest Common Subsequence',lc:'https://leetcode.com/problems/longest-common-subsequence/',gfg:'https://practice.geeksforgeeks.org/problems/longest-common-subsequence-1587115620/1'},
      {name:'Longest Common Substring',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/longest-common-substring1452/1'},
      {name:'Longest Palindromic Subsequence',lc:'https://leetcode.com/problems/longest-palindromic-subsequence/',gfg:'N/A'},
      {name:'Minimum Insertions to Make String Palindrome',lc:'https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/',gfg:'N/A'},
      {name:'Shortest Common Supersequence',lc:'https://leetcode.com/problems/shortest-common-supersequence/',gfg:'N/A'},
      {name:'Distinct Subsequences',lc:'https://leetcode.com/problems/distinct-subsequences/',gfg:'N/A'},
      {name:'Edit Distance',lc:'https://leetcode.com/problems/edit-distance/',gfg:'https://practice.geeksforgeeks.org/problems/edit-distance3702/1'},
      {name:'Wildcard Matching',lc:'https://leetcode.com/problems/wildcard-matching/',gfg:'N/A'},
    ]},
    {id:'s16-5',title:'16.5 · DP on Stocks',problems:[
      {name:'Best Time to Buy and Sell Stock (I)',lc:'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',gfg:'N/A'},
      {name:'Best Time to Buy and Sell Stock (II)',lc:'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/',gfg:'N/A'},
      {name:'Buy and Sell Stocks (III) — At Most 2 Transactions',lc:'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/',gfg:'N/A'},
      {name:'Buy and Sell Stocks (IV) — At Most K Transactions',lc:'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/',gfg:'N/A'},
      {name:'Buy and Sell Stocks with Cooldown',lc:'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/',gfg:'N/A'},
      {name:'Buy and Sell Stocks with Transaction Fee',lc:'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/',gfg:'N/A'},
    ]},
    {id:'s16-6',title:'16.6 · DP on LIS',problems:[
      {name:'Longest Increasing Subsequence',lc:'https://leetcode.com/problems/longest-increasing-subsequence/',gfg:'https://practice.geeksforgeeks.org/problems/longest-increasing-subsequence-1587115620/1'},
      {name:'LIS using Binary Search',lc:'https://leetcode.com/problems/longest-increasing-subsequence/',gfg:'N/A'},
      {name:'Largest Divisible Subset',lc:'https://leetcode.com/problems/largest-divisible-subset/',gfg:'N/A'},
      {name:'Longest String Chain',lc:'https://leetcode.com/problems/longest-string-chain/',gfg:'N/A'},
      {name:'Longest Bitonic Subsequence',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/longest-bitonic-subsequence0824/1'},
      {name:'Number of LIS',lc:'https://leetcode.com/problems/number-of-longest-increasing-subsequence/',gfg:'N/A'},
    ]},
    {id:'s16-7',title:'16.7 · MCM DP | Partition DP',problems:[
      {name:'Matrix Chain Multiplication',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/matrix-chain-multiplication0303/1'},
      {name:'Minimum Cost to Cut the Stick',lc:'https://leetcode.com/problems/minimum-cost-to-cut-a-stick/',gfg:'N/A'},
      {name:'Burst Balloons',lc:'https://leetcode.com/problems/burst-balloons/',gfg:'N/A'},
      {name:'Evaluate Boolean Expression to True',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/boolean-parenthesization5610/1'},
      {name:'Palindrome Partitioning II',lc:'https://leetcode.com/problems/palindrome-partitioning-ii/',gfg:'N/A'},
      {name:'Partition Array for Maximum Sum',lc:'https://leetcode.com/problems/partition-array-for-maximum-sum/',gfg:'N/A'},
    ]},
    {id:'s16-8',title:'16.8 · DP on Squares',problems:[
      {name:'Maximal Square',lc:'https://leetcode.com/problems/maximal-square/',gfg:'N/A'},
      {name:'Count Square Submatrices with All Ones',lc:'https://leetcode.com/problems/count-square-submatrices-with-all-ones/',gfg:'N/A'},
    ]},
  ]},
  {id:'s17',step:17,title:'Tries',color:'#f97316',icon:'🌿',
  subsections:[
    {id:'s17-1',title:'17.1 · Theory',problems:[
      {name:'Introduction to Trie',lc:'https://leetcode.com/problems/implement-trie-prefix-tree/',gfg:'https://practice.geeksforgeeks.org/problems/trie-insert-and-search0651/1'},
      {name:'Implement Trie I (Insert, Search, StartsWith)',lc:'https://leetcode.com/problems/implement-trie-prefix-tree/',gfg:'https://practice.geeksforgeeks.org/problems/trie-insert-and-search0651/1'},
      {name:'Implement Trie II',lc:'N/A',gfg:'N/A'},
    ]},
    {id:'s17-2',title:'17.2 · Problems',problems:[
      {name:'Longest String with All Prefixes',lc:'N/A',gfg:'N/A'},
      {name:'Number of Distinct Substrings in a String',lc:'N/A',gfg:'https://practice.geeksforgeeks.org/problems/number-of-distinct-substrings-in-a-string/1'},
      {name:'Maximum XOR of Two Numbers in an Array',lc:'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/',gfg:'N/A'},
      {name:'Maximum XOR with an Element from Array',lc:'https://leetcode.com/problems/maximum-xor-with-an-element-from-array/',gfg:'N/A'},
    ]},
  ]},
];
